# Generated by Django 6.1 on 2026-08-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
