# Generated by Django 6.1 on 2026-08-06 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('pausa_inicio', 'Início de Pausa'), ('pausa_fim', 'Fim de Pausa')], max_length=20)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
