# Generated by Django 6.1 on 2026-08-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
