# Generated by Django 6.1 on 2026-08-07 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options_remove_itempedido_observacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='garcom',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'garcom'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='token_qrcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto / Na Mesa'), ('enviado', 'Enviado à Cozinha'), ('pronto', 'Pronto para Entrega'), ('entregue', 'Entregue'), ('fechado', 'Fechado / Conta Paga'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
