# Generated by Django 6.1 on 2026-08-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_cliente_fornecedor_alter_pedido_options_and_more'),
        ('rh', '0002_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='garcom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='rh.funcionario'),
        ),
    ]
