# Generated by Django 6.1 on 2026-08-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_garcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
