# Generated by Django 6.1 on 2026-08-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_itempedido_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('preparacao', 'Em Preparação'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
