# Generated by Django 6.1 on 2026-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='CNPJ/CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Razão Social / Nome'),
        ),
    ]
