# Generated by Django 6.1 on 2026-08-08 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relogioponto', '0001_initial'),
        ('rh', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['-data_hora']},
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='saida',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_ALMOCO', 'Saída Almoço'), ('RETORNO_ALMOCO', 'Retorno Almoço'), ('SAIDA', 'Saída')], default='ENTRADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='rh.funcionario'),
        ),
    ]
