# Generated by Django 6.1 on 2026-08-10 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relogioponto', '0002_alter_registroponto_options_and_more'),
        ('rh', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Registro de Ponto', 'verbose_name_plural': 'Registros de Ponto'},
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='rh.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_ALMOCO', 'Saída Almoço'), ('RETORNO_ALMOCO', 'Retorno Almoço'), ('SAIDA', 'Saída'), ('HORA_EXTRA', 'Hora Extra')], max_length=20, verbose_name='Tipo de Registro'),
        ),
    ]
