# Generated by Django 6.1 on 2026-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='token_qrcode',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(default='livre', max_length=50),
        ),
    ]
