# Generated by Django 6.1 on 2026-08-09 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_token_qrcode_alter_mesa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='token_qrcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
